name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
        run: |
            echo "${SSH_PRIVATE_KEY}" > private_key
            chmod 600 private_key
            ssh -i private_key -o StrictHostKeyChecking=no ${USERNAME}@${HOST} "cd /home/user/htdocs/bordadeiras && git pull && composer install --no-dev && php artisan migrate --force && php artisan config:clear && php artisan route:cache && php artisan view:cache && php artisan db:seed --force"
            rm private_key
