name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
        run: |
            echo "${SSH_PRIVATE_KEY}" > private_key
            chmod 600 private_key
            rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --exclude=node_modules --exclude=storage --exclude=vendor . ${USERNAME}@${HOST}:/home/user/htdocs/bordadeiras
            ssh -i private_key -o StrictHostKeyChecking=no ${USERNAME}@${HOST} "cd /home/user/htdocs/bordadeiras && composer install --no-dev && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
            rm private_key
